import { TemplateConfig } from '../types/template';

export const DEFAULT_TEMPLATES: TemplateConfig[] = [
  {
    id: 'template_1_blue_wave',
    name: 'Deep Ocean Blue Wave',
    backgroundUrl: '/templates/template_1_blue_wave.jpg',
    width: 1080,
    height: 1080,
    theme: 'blue',
    zones: [
      {
        id: 'business_name',
        type: 'text',
        x: 140,
        y: 60,
        width: 800,
        height: 65,
        fontSize: 32,
        fontWeight: 700,
        align: 'center',
        color: '#FACC15',
        badgeStyle: 'pill',
        badgeBg: 'rgba(10, 25, 60, 0.90)',
        badgeBorder: '#FACC15',
        badgeRadius: 32,
      },
      {
        id: 'headline',
        type: 'text',
        x: 90,
        y: 155,
        width: 900,
        height: 95,
        fontSize: 44,
        fontWeight: 800,
        align: 'center',
        color: '#FACC15',
        strokeColor: '#0A193C',
        strokeWidth: 3,
      },
      {
        id: 'subtitle',
        type: 'text',
        x: 100,
        y: 255,
        width: 880,
        height: 60,
        fontSize: 24,
        fontWeight: 600,
        align: 'center',
        color: '#FFFFFF',
      },
      {
        id: 'product_image',
        type: 'image',
        x: 160,
        y: 335,
        width: 760,
        height: 385,
        fit: 'contain',
        badgeStyle: 'card',
        badgeBg: 'rgba(10, 25, 60, 0.88)',
        badgeBorder: '#FACC15',
        badgeRadius: 20,
      },
      {
        id: 'offer',
        type: 'text',
        x: 350,
        y: 755,
        width: 380,
        height: 105,
        fontSize: 40,
        fontWeight: 900,
        align: 'center',
        color: '#0A193C',
        badgeStyle: 'rosette',
        badgeBg: '#FACC15',
        badgeBorder: '#FFFFFF',
      },
      {
        id: 'cta',
        type: 'text',
        x: 160,
        y: 895,
        width: 760,
        height: 70,
        fontSize: 28,
        fontWeight: 700,
        align: 'center',
        color: '#FFFFFF',
        badgeStyle: 'pill',
        badgeBg: '#0A193C',
        badgeBorder: '#FACC15',
        badgeRadius: 20,
      },
      {
        id: 'contact',
        type: 'text',
        x: 60,
        y: 995,
        width: 960,
        height: 58,
        fontSize: 18,
        fontWeight: 700,
        align: 'center',
        color: '#0A193C',
        badgeStyle: 'pill',
        badgeBg: 'rgba(255, 255, 255, 0.96)',
        badgeBorder: 'rgba(10, 25, 60, 0.35)',
        badgeRadius: 29,
      },
    ],
  },
  {
    id: 'template_2_cyan_fluid',
    name: 'Light Cyan Fluid Glow',
    backgroundUrl: '/templates/template_2_cyan_fluid.jpg',
    width: 1080,
    height: 1080,
    theme: 'cyan',
    zones: [
      {
        id: 'business_name',
        type: 'text',
        x: 140,
        y: 60,
        width: 800,
        height: 65,
        fontSize: 32,
        fontWeight: 700,
        align: 'center',
        color: '#075985',
        badgeStyle: 'pill',
        badgeBg: 'rgba(255, 255, 255, 0.95)',
        badgeBorder: '#0369A1',
        badgeRadius: 32,
      },
      {
        id: 'headline',
        type: 'text',
        x: 90,
        y: 155,
        width: 900,
        height: 95,
        fontSize: 44,
        fontWeight: 800,
        align: 'center',
        color: '#082F49',
        strokeColor: 'rgba(255, 255, 255, 0.95)',
        strokeWidth: 2,
      },
      {
        id: 'subtitle',
        type: 'text',
        x: 100,
        y: 255,
        width: 880,
        height: 60,
        fontSize: 24,
        fontWeight: 600,
        align: 'center',
        color: '#0369A1',
      },
      {
        id: 'product_image',
        type: 'image',
        x: 160,
        y: 335,
        width: 760,
        height: 385,
        fit: 'contain',
        badgeStyle: 'card',
        badgeBg: 'rgba(240, 253, 255, 0.96)',
        badgeBorder: '#0284C7',
        badgeRadius: 20,
      },
      {
        id: 'offer',
        type: 'text',
        x: 350,
        y: 755,
        width: 380,
        height: 105,
        fontSize: 40,
        fontWeight: 900,
        align: 'center',
        color: '#082F49',
        badgeStyle: 'rosette',
        badgeBg: '#F59E0B',
        badgeBorder: '#FFFFFF',
      },
      {
        id: 'cta',
        type: 'text',
        x: 160,
        y: 895,
        width: 760,
        height: 70,
        fontSize: 28,
        fontWeight: 700,
        align: 'center',
        color: '#FFFFFF',
        badgeStyle: 'pill',
        badgeBg: '#082F49',
        badgeBorder: '#38BDF8',
        badgeRadius: 20,
      },
      {
        id: 'contact',
        type: 'text',
        x: 60,
        y: 995,
        width: 960,
        height: 58,
        fontSize: 18,
        fontWeight: 700,
        align: 'center',
        color: '#082F49',
        badgeStyle: 'pill',
        badgeBg: 'rgba(255, 255, 255, 0.96)',
        badgeBorder: 'rgba(8, 47, 73, 0.35)',
        badgeRadius: 29,
      },
    ],
  },
  {
    id: 'template_3_radial_wave',
    name: 'Radial Wave Halftone',
    backgroundUrl: '/templates/template_3_radial_wave.jpg',
    width: 1080,
    height: 1080,
    theme: 'purple',
    zones: [
      {
        id: 'business_name',
        type: 'text',
        x: 140,
        y: 60,
        width: 800,
        height: 65,
        fontSize: 32,
        fontWeight: 700,
        align: 'center',
        color: '#2E1065',
        badgeStyle: 'pill',
        badgeBg: 'rgba(255, 255, 255, 0.95)',
        badgeBorder: '#7C3AED',
        badgeRadius: 32,
      },
      {
        id: 'headline',
        type: 'text',
        x: 90,
        y: 155,
        width: 900,
        height: 95,
        fontSize: 44,
        fontWeight: 800,
        align: 'center',
        color: '#3B0764',
        strokeColor: 'rgba(255, 255, 255, 0.95)',
        strokeWidth: 2,
      },
      {
        id: 'subtitle',
        type: 'text',
        x: 100,
        y: 255,
        width: 880,
        height: 60,
        fontSize: 24,
        fontWeight: 600,
        align: 'center',
        color: '#312E81',
      },
      {
        id: 'product_image',
        type: 'image',
        x: 160,
        y: 335,
        width: 760,
        height: 385,
        fit: 'contain',
        badgeStyle: 'card',
        badgeBg: 'rgba(250, 245, 255, 0.96)',
        badgeBorder: '#7C3AED',
        badgeRadius: 20,
      },
      {
        id: 'offer',
        type: 'text',
        x: 350,
        y: 755,
        width: 380,
        height: 105,
        fontSize: 40,
        fontWeight: 900,
        align: 'center',
        color: '#1E1B4B',
        badgeStyle: 'rosette',
        badgeBg: '#F59E0B',
        badgeBorder: '#FFFFFF',
      },
      {
        id: 'cta',
        type: 'text',
        x: 160,
        y: 895,
        width: 760,
        height: 70,
        fontSize: 28,
        fontWeight: 700,
        align: 'center',
        color: '#FFFFFF',
        badgeStyle: 'pill',
        badgeBg: '#3B0764',
        badgeBorder: '#C084FC',
        badgeRadius: 20,
      },
      {
        id: 'contact',
        type: 'text',
        x: 60,
        y: 995,
        width: 960,
        height: 58,
        fontSize: 18,
        fontWeight: 700,
        align: 'center',
        color: '#2E1065',
        badgeStyle: 'pill',
        badgeBg: 'rgba(255, 255, 255, 0.96)',
        badgeBorder: 'rgba(46, 16, 101, 0.35)',
        badgeRadius: 29,
      },
    ],
  },
  {
    id: 'template_4_green_curve',
    name: 'Fresh Lime & Emerald Curve',
    backgroundUrl: '/templates/template_4_green_curve.jpg',
    width: 1080,
    height: 1080,
    theme: 'green',
    zones: [
      {
        id: 'business_name',
        type: 'text',
        x: 140,
        y: 60,
        width: 800,
        height: 65,
        fontSize: 32,
        fontWeight: 700,
        align: 'center',
        color: '#064E3B',
        badgeStyle: 'pill',
        badgeBg: 'rgba(255, 255, 255, 0.95)',
        badgeBorder: '#059669',
        badgeRadius: 32,
      },
      {
        id: 'headline',
        type: 'text',
        x: 90,
        y: 155,
        width: 900,
        height: 95,
        fontSize: 44,
        fontWeight: 800,
        align: 'center',
        color: '#022C22',
        strokeColor: 'rgba(255, 255, 255, 0.95)',
        strokeWidth: 2,
      },
      {
        id: 'subtitle',
        type: 'text',
        x: 100,
        y: 255,
        width: 880,
        height: 60,
        fontSize: 24,
        fontWeight: 600,
        align: 'center',
        color: '#064E3B',
      },
      {
        id: 'product_image',
        type: 'image',
        x: 160,
        y: 335,
        width: 760,
        height: 385,
        fit: 'contain',
        badgeStyle: 'card',
        badgeBg: 'rgba(240, 253, 244, 0.96)',
        badgeBorder: '#059669',
        badgeRadius: 20,
      },
      {
        id: 'offer',
        type: 'text',
        x: 350,
        y: 755,
        width: 380,
        height: 105,
        fontSize: 40,
        fontWeight: 900,
        align: 'center',
        color: '#022C22',
        badgeStyle: 'rosette',
        badgeBg: '#FACC15',
        badgeBorder: '#022C22',
      },
      {
        id: 'cta',
        type: 'text',
        x: 160,
        y: 895,
        width: 760,
        height: 70,
        fontSize: 28,
        fontWeight: 700,
        align: 'center',
        color: '#FFFFFF',
        badgeStyle: 'pill',
        badgeBg: '#022C22',
        badgeBorder: '#34D399',
        badgeRadius: 20,
      },
      {
        id: 'contact',
        type: 'text',
        x: 60,
        y: 995,
        width: 960,
        height: 58,
        fontSize: 18,
        fontWeight: 700,
        align: 'center',
        color: '#022C22',
        badgeStyle: 'pill',
        badgeBg: 'rgba(255, 255, 255, 0.96)',
        badgeBorder: 'rgba(2, 44, 34, 0.35)',
        badgeRadius: 29,
      },
    ],
  },
];
